config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/test', to: 'one_off_products#test_item'
  get '/test-index', to: 'one_off_products#test_index'
  delete '/test', to: 'carts#post_destroy'
  get '/test-index', to:'carts#post_index'
  get '/test-checkout', to: 'carts#post_checkout'
  post '/test-checkout', to: 'carts#post_complete_checkout'
  get '/send-test-email', to: 'carts#test_email'
  get '/beta-mailing-list', to: 'static_pages#beta_test_list'
  get '/home-signup-successful', to: 'stripe_connect_user#new'
  get '/our-team', to: 'static_pages#our_team'
  # get '/add-to-cart', to: 'carts#add_to_cart'
  post '/add-to-cart', to: 'carts#add_to_cart'
  get '/guest-add-to-cart', to: 'carts#guest_add_to_cart'
  post '/guest-add-to-cart', to: 'carts#post_guest_add_to_cart'
  get '/guest-cart', to: 'carts#guest_cart_index'
  delete '/guest-cart', to: 'carts#guest_destroy'
  get '/guest-checkout', to: 'carts#guest_checkout'
  post '/guest-checkout', to: 'carts#guest_complete_checkout'
  get 'add-subscription-to-cart', to: 'carts#add_to_cart_subscription'
  get '/checkout', to: 'carts#checkout'
  post '/checkout', to: 'carts#complete_checkout'
  get '/successful-checkout', to: 'cartss#successful_checkout'
  get '/unsuccessful-checkout', to: 'carts#unsuccessful_checkout'
  get '/cart', to: 'carts#index'
  delete '/cart', to: 'carts#destroy'
  get '/contact', to: 'static_pages#contact'
  get '/contact-test', to: 'static_pages#contact_test'
  post '/contact', to: 'static_pages#create'
  get '/services', to: 'static_pages#partners'
  post '/services', to: 'static_pages#partners_create'
  get '/partner-contact', to: 'static_pages#partner_contact'
  get '/terms-of-service', to: 'static_pages#terms_of_service'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/stripe-partners', to: 'static_pages#stripe_partner_info'
  get '/start-your-mealkit-program', to: 'static_pages#start_your_mealkit_program'
  get '/signup-info', to: 'users#business_or_customer'
  post '/signup-info', to: 'users#business_or_customer_create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # get '/plan-types', to: 'plan_types#index'
  get '/mealkits', to: 'products#index'
  get '/additional-products', to: 'one_off_products#index'
  get '/partners', to: 'partner_logos#index'
  get '/mealkit-playbook', to: 'partner_logos#playbook'
  post '/mealkit-playbook', to: 'partner_logos#download_playbook'
  resources :users
  resources :stripe_connect_users
  get '/successful-subscription-purchase', to: 'plan_types#successful_subscription_purchase'
  get '/unsuccessful-subscription-purchase', to: 'plan_types#unsuccessful_subscription_purchase'
  #Below routes specifically for product library
  # resources :products, only: [:index]
  #little bit of logic to determine where you should go
  resources :products do
    member do
      put "add", to: "products#library"
      put "remove", to: "products#library"
    end
  end
  #Look into the pricing controller needed here?
  # Resources pricing, only: [:index]
  resources :one_off_products
  resources :products
  resources :product_subscription_library, only: [:index] 

  ####MEAL KIT PLAN ROUTE SETUP######
  resources :plan_types do
    member do
      put "add", to: "plan_types#library"
      put "remove", to: "plan_types#library"
    end
  end
  resources :plan_types 
  resources :plan_subscription_library, only: [:index]
  resources :carts
  resources :partners, param: :name
  resources :partner_backgrounds

  ######BASIC SETUP ROUTES#######
  resources :subscriptions
  resources :purchase_one_offs
  resources :partner_logos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contact_emails, only: [:edit]

  #For Sitemap capture
  get '/sitemap.xml.gz', to: redirect("https://markitplace-sitemaps.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz")
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :admin_user,     only: :stripe_partner_info
  
  def home
  end

  def our_team
  end

  def contact
  end

  def contact_test
  end

  def partners
  end

  def partner_contact 
  end

  #Functions specific for terms of service and privacy policies
  def terms_of_service
  end

  def privacy_policy
  end

  def beta_test_list
  end

  def start_your_mealkit_program
  end

  def stripe_partner_info
    @stripe_users = StripeConnectUser.all
  end

  def create
    UserMailer.contact_support(params[:contact][:contact_name], params[:contact][:contact_email], params[:contact][:contact_how], params[:contact][:contact_help]).deliver_now
    redirect_to contact_url
    flash[:success] = "Your message has been received. We will be in contact shortly."
  end

  def partners_create
    UserMailer.partners_contact_support(params[:partners][:partner_name], params[:partners][:partner_email], params[:partners][:partner_location], params[:partners][:partner_food_type],params[:partners][:partner_post_offering],params[:partners][:partner_analytics],params[:partners][:partner_brand_management]).deliver_now
    redirect_to partner_contact_url
    flash[:success] = "Your message has been received. We will be in contact shortly."
  end


  private
  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/beta_test_list.html.erb
<div class = "row justify-contentceter">
    <div class= "col-12 header text-center">
        <h1 class="title-mobile"> Beta Mailing List </h1>
    </div>
    <div class = "d-none d-lg-block col-lg-3">
        <span></span>
    </div>
    <div class= "col-12 col-lg-6 header text-center">
        <iframe src="https://docs.google.com/forms/d/e/1FAIpQLSfxhqOZFAiCGJG1I0wKkgT2DX9S_hcud9Z10J4ks4Wkaa3XzQ/viewform?embedded=true" width="640" height="433" frameborder="0" marginheight="0" marginwidth="0">Loading…</iframe>
    </div>
</div>

app/views/static_pages/contact-test.html.erb
<use xlink:href="https://www.walkersands.com/wp-content/themes/_ws/imgs/sprite.svg#branding"></use>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<div class="contact-us">
<section class="jumbotron jumbotron-fluid" id="jumbotron-contact">
  <div class="container">
    <div class="row justify-content-end">
      <div class="col-6 col-lg-6">
        <h1 class="homepage-text shadow-underscore jumbo-maintext title-mobile">CUSTOMER CONTACT</h1>
        <h3 class ="homepage-text pt-3 pb-3 jumbo-subtext subtitle-description-mobile">We love hearing from our users! Contact us
          anytime and we will get back to you as soon as possible.</h3>
      </div>
    </div>
  </div>
</section>
<div class="container">
  <div class="row">
    <div class="col-12 col-lg-8">
      <div class="form-block">
        <%= form_for(:contact, url: contact_path) do |f| %>
          <div class="text-block pb-3 subtitle-description-mobile">
            Please fill out the form below with how we can help you today and a support specialist will contact you shorty. Thank you!
          </div>
          <%= f.label :contact_name, class: 'field-label emphasis contact-form-item-mobile' do %>
            <span class = 'field-label emphasis'> Name </span><br>
          <% end %><br>
          <%= f.text_field :contact_name, class: 'form-control form-control-mobile', placeholder: "Name" %><br>
          <%= f.label :contact_email, class: 'field-label emphasis contact-form-item-mobile' do %>
            <span class = 'field-label emphasis'> Email </span><br>
          <% end %><br>
          <%= f.email_field :contact_email, class: 'form-control form-control-mobile', placeholder: "Email" %><br>
          <%= f.label :contact_how, class: 'field-label emphasis contact-form-item-mobile' do %>
            <span class = 'field-label emphasis'> How did you hear about Markitplace? </span><br>
          <% end %><br>
          <%= f.text_area :contact_how, class: 'form-control text-area-mobile', placeholder: "Did you hear about us from friends, ads, or an email campaign?"  %><br>
          <%= f.label :contact_help, class: 'field-label emphasis contact-form-item-mobile' do %>
            <span class = 'field-label emphasis'> How can we help you?</span><br>
          <% end %><br>
          <%= f.text_area :contact_help, class: 'form-control text-area-mobile', placeholder: "Please explain and we will get back to you as quickly as possible."  %><br>
          <%= f.submit "Submit", class: "btn btn-success jumbo-button mt-2 btn-mobile" %><br>
        <% end %>
      </div>
    </div>
    <div class="d-none d-lg-block col-lg-4">
      <div class="lets-chat-title">
        Let&apos;s chat.
      </div>
      <div class="lets-chat">
        +1 (207) 767-3433 <br>
        admin@markitplace.io
      </div>
      <div class="lets-chat">
        Markitplace Corporation<br>
        90 State Street<br>
        STE 700 Office 40<br>
        Albany, NY<br>
        12207
      </div>
    </div>
  </div>
</div>
</div>

app/views/static_pages/contact_test.html.erb
<% provide(:title, "Services") %>
<div class="partners">
    <section class="jumbotron jumbotron-fluid" id="jumbotron-contact">
    <div class="container">
        <div class="row justify-content-end">
        <div class="col-12 col-lg-6" >
            <h1 class="homepage-text shadow-underscore jumbo-maintext">SERVICES FOR PARTNERS</h1>
            <h3 class ="homepage-text pt-3 pb-3 jumbo-subtext">Markitplace is a platform designed to increase revenue and exposure for non on-demand food delivery companies.
            We help grow our partner&#39;s customer base through our platform and provide insightful analytics on industry
            trends and customer needs</h3>
        </div>
        </div>
    </div>
    </section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-sm-12 col-md-6 align-items-stretch pb-5">
                <h3>Inspiring Growth</h3>
                <p>Markitplace<sup class="shrink">©</sup> offers our partners a fully managed platform where they can advertise their products and reach a larger customer base. Our team also leverages
                search engine optimization and digital marketing campaigns to boost the exposure of our partners.
                </p>
                <%= link_to "LEARN MORE", partner_contact_path, class: "btn btn-outline-success jumbo-button" %>
            </div>
            <div class="col-sm-12 col-md-6 align-items-stretch pb-5">
                <h3>Analytics</h3>
                <p>Monthly Analytics reports will include success of growth campaigns and other key metrics around the performance of the partnership. Our platform
                also actively seeks out user feedback which is condensed and presented to our partners so they can make actionable.
                </p>
                <%= link_to "LEARN MORE", partner_contact_path, class: "btn btn-outline-success jumbo-button" %>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>Pricing</h3>
                <p>Clients are not charged anything to have their product posted on our platform, instead clients are charged on a per booking basis every time a meal/subscription
                is purchased through the Markitplace<sup class="shrink">©</sup> platform. For specifics on pricing, please reach out to our support team.
                </p>
                <%= link_to "LEARN MORE", partner_contact_path, class: "btn btn-outline-success jumbo-button" %>
            </div>
            <div class="col-sm-12 col-md-6">
                <h3>Value</h3>
                <p>By helping companies boost their exposure and open up a new revenue stream, Markitplace<sup class="shrink">©</sup> gives clients more time to focus on what makes them great. 
                With Markitplace<sup class="shrink">©</sup> you can continue to maintain and build upon the same great brand your customers love. 
                </p>
                <%= link_to "LEARN MORE", partner_contact_path, class: "btn btn-outline-success jumbo-button" %>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="homepage">
    <div class="homepage-2019">
        <section class="jumbotron jumbotron-fluid home-jumbotron jumbotron-mobile">
          <div class="container">
            <div class="row text-left">
              <div class="col-8 col-lg-6 justify-content-center" id="jumbo-textbox">
                <h1 class="homepage-text shadow-underscore jumbo-maintext title-mobile">Food from Local Chefs in Your Area</h1>
                <h3 class ="homepage-text pt-3 pb-3" id ="jumbo-subtext">We vet, research and connect you with the best chefs in your community so you can get 
                restaurant-quality food within the comfort of your home.</h3>
                <%= link_to "START SHOPPING", partners_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
              </div>
            </div>
          </div>
        </section>
        <div class="container" id="our-process">
          <div class="row pb-3">
            <div class="col-12 pb-4">
              <section>
                <p class="text-center subtext-gray description-text-mobile pb-1">
                  Markitplace works with scheduled food delivery companies to provide you the widest array of food options. Our partners then deliver
                  fresh food products straight to you. You can also be assured everytime you buy your money isn&apos;t going into the hands
                  of some large corporation, but towards a <span style = "color:green"><strong>small business in your community.</strong></span>
                </p>
                <h2 class="text-center mobile-hidden" style = "color: #595959">A delicious meal is only a few steps away</h2>
              </section>
            </div>
          </div>
            <div class="row pb-3 justify-content-center">
              <div class="col-12 col-lg-8" data-aos="fade-right" data-aos-easing="ease-in-sine">
                <h3>Choose</h3>
                <p class="description-text-mobile">
                    Markitplace acts as your search engine for meal kits and prepared meals from small
                    businesses in your area. <span style = "color:green"><strong>Choose</strong></span> your meal and read about the small business that you&apos;re supporting.
                </p>
              </div>
              <div class="d-none d-lg-block col-lg-4">
                <%= image_tag("choose.png", class: "img-fluid", alt:"Mealkit-choose") %>
              </div>
            </div>
            <div class="row pb-3">
              <div class="d-none d-lg-block col-lg-4">
                <%= image_tag("unpack.png", class: "img-fluid", alt:"Mealkit-unpack") %>
              </div>
              <div class="col-12 col-lg-8" data-aos="fade-left" data-aos-easing="ease-in-sine">
                <h3>Unpack</h3>
                <p class="description-text-mobile">
                    Our partners will deliver or ship your kit directly to your door. <span style = "color:green"><strong>Unpack</strong></span> your box with premium, pre-prepared and certifiably fresh food products. Simply follow the included
                    instructions and you'll have a delicious, home cooked meal fully prepared.
                </p>
              </div>
            </div>
            <div class = "row pb-3">
              <div class="col-12 col-lg-8" data-aos="fade-right" data-aos-easing="ease-in-sine">
                <h3>Eat & Enjoy!</h3>
                <p class="description-text-mobile">
                    <span style = "color:green"><strong>Enjoy</strong></span> restaurant-quality food in the comfort of your home. With new, affordable meals
                    every week from our network of partners you&apos;ll not only have access to a wide variety of meals, but you&apos;ll
                    also be supporting your community. 
                </p>
              </div>
              <div class="d-none d-lg-block col-lg-4">
                <%= image_tag("enjoy.png", class: "img-fluid", alt:"Mealkit-enjoy") %>
              </div>
              <div class="col-12 text-center pt-3">
              <%= link_to "START SHOPPING", one_off_products_path, class: "btn btn-success jumbo-button btn-mobile" %>
              </div>
            </div>
          </div<
        </div>
      </div>
    </div>
</div>

app/views/static_pages/our_team.html.erb
<% provide(:title, "Our Team") %>
<div class="our-team">
      <section class="jumbotron jumbotron-fluid" id="jumbotron-team">
        <div class="container">
          <div class="row justify-content-end">
            <div class="col-8 col-lg-6" >
              <h1 class="homepage-text title-mobile shadow-underscore jumbo-maintext">MEET THE TEAM</h1>
              <h3 class ="subtitle-description-mobile homepage-text pt-3 pb-3 jumbo-subtext">We're entrepreneurs passionate about tech, food, and supporting small business. Our
                platform embodies these passions and we're continually striving to improve it.</h3>
            </div>
          </div>
        </div>
      </section>
      <div class = "container">
        <div class="row justify-content-center">
          <div class="col-10 col-lg-4 text-center border-shadow margin-nonmobile-right">
              <%= image_tag("dan-founder-m2.jpg", class: "img-rounded img-fluid headshot-border", alt:"founder-and-CTO") %>
              <div class= "pt-3">
                <div class="adjust-size founder-description-mobile text-center" style="display: inline-block">
                  <h5 class="founder-description-mobile">Daniel Brett, Co-Founder</h5>
                  <p class="subtext-about about-description-mobile">
                    Daniel graduated from Boston College in 2018 with a Bachelor's Degree in Computer Science. Before starting Markitplace
                    Daniel worked in Boston as a security engineer for Oracle Corporation. An EMT, Daniel has
                    an interest in both tech and health and is continually looking to combine them in new and creative ways.
                  </p>
                  <a href="https://www.linkedin.com/in/daniel-brett-51669b126/" target="_blank" class="btn btn-lg btn-mobile my-auto mt-auto"><i class="fab fa-linkedin fa-lg"></i></a>
                </div>
              </div>
          </div>
          <div class="col-10 col-lg-4 text-center border-shadow border-shadow margin-nonmobile-left">
              <%= image_tag("bobby-founder-m.jpg", class: "img-rounded img-fluid headshot-border", alt:"founder-and-CFO") %>
              <div class= "pt-3">
                <div class= "adjust-size founder-description-mobile text-center">
                  <h5 class="founder-description-mobile">Robert Harrington, Co-Founder</h5>
                  <p class="subtext-about about-description-mobile">
                    Robert graduated from Boston College in 2018 with a Bachelor's Degree in Economics. Before starting Markitplace he worked as a
                    broker in New York City on the Interest Rate Swap Options Desk. Robert enjoys snowboarding on the weekends and holds himself over 
                    by swimming and playing tennis until first snowfall.
                  </p>
                  <a href="https://www.linkedin.com/in/robert-harrington-6b731b125/" target="_blank" class="btn btn-lg btn-mobile my-auto mt-auto"><i class="fab fa-linkedin fa-lg"></i></a>
                </div>
              </div>
          </div>
        </div>
      </div>
    </div>

app/views/static_pages/partner_contact.html.erb
<% provide(:title, "Services") %>
<div class="partners">
    <section class="jumbotron jumbotron-fluid" id="jumbotron-contact">
        <div class="container">
            <div class="row justify-content-end">
                <div class="col-6 col-lg-6" >
                    <h1 class="homepage-text shadow-underscore jumbo-maintext title-mobile">PARTNER CONTACT</h1>
                    <h3 class ="homepage-text pt-3 pb-3 jumbo-subtext partner-text-mobile">Interested in partnering with us? Fill out the form below and one of our
                    specialists will contact you about our services.</h3>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <div class="form-block">
                    <%= form_for(:partners, url: services_path) do |f| %>
                        <div class="text-block pb-3">
                            Please fill out the form below with how we can help you today and a support specialist will contact you shorty. Thank you!
                        </div>
                        <%= f.label :partner_name, class: 'field-label emphasis contact-form-item-mobile' do %>
                            <span class = 'field-label emphasis'> Name </span><br>
                        <% end %><br>
                        <%= f.text_field :partner_name, class: 'form-control form-control-mobile', placeholder: "Name" %><br>
                        <%= f.label :partner_email, class: 'field-label emphasis contact-form-item-mobile' do %>
                            <span class = 'field-label emphasis'> Email </span><br>
                        <% end %><br>
                        <%= f.email_field :partner_email, class: 'form-control form-control-mobile', placeholder: "Email" %><br>
                        <%= f.label :partner_location, class: 'field-label emphasis contact-form-item-mobile' do %>
                            <span class = 'field-label emphasis'> Where are you based? </span><br>
                        <% end %><br>
                        <%= f.text_field :partner_location, class: 'form-control form-control-mobile', placeholder: "New York City, NY"  %><br>
                        <%= f.label :partner_food_type, class: 'field-label emphasis contact-form-item-mobile' do %>
                            <span class = 'field-label emphasis'> Does your company specialize in a specific type of cuisine? If so, what?</span><br>
                        <% end %><br>
                        <%= f.text_area :partner_food_type, class: 'form-control text-area-mobile', placeholder: "Please give us some background on the food you prepare."  %><br>
                        <%= f.label :partner_services_interest, class: 'field-label emphasis contact-form-item-mobile' do %>
                            <span class = 'field-label emphasis'>Which services are you interested in?</span><br>
                        <% end %><br>
                        <%= f.check_box :partner_post_offering, class: "checkboxtext checkbox-mobile"%>
                        <%= f.label :partner_post_offering, class: "checkbox-item-mobile" do %>
                            <span> Post your offerings on our platform</span>
                        <% end %><br>
                        <%= f.check_box :partner_analytics, class: "checkboxtext checkbox-mobile"%>
                        <%= f.label :partner_analytics, class: "checkbox-item-mobile" do %>
                            <span> Analytics Reports </span>
                        <% end %><br>
                        <%= f.check_box :partner_brand_management, class: "checkboxtext checkbox-mobile"%>
                        <%= f.label :partner_brand_management, class: "checkbox-item-mobile" do %>
                            <span> Media & Brand Management </span>
                        <% end %><br>
                        
                        <%= f.submit "Submit", class: "btn btn-success jumbo-button mt-2 btn-mobile async-button", id: "asyncBtn", data: {disable_with: "Processing Request"} %><br>
                    <% end %>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/partners.html.erb
<% provide(:title, "Services") %>
<div class="partners">
    <section class="jumbotron jumbotron-fluid" id="jumbotron-contact">
    <div class="container">
        <div class="row justify-content-end">
        <div class="col-6 col-lg-6" >
            <h1 class="homepage-text shadow-underscore jumbo-maintext title-mobile">APPLY TO BECOME A CHEF</h1>
            <h3 class ="d-none d-lg-block homepage-text pt-3 pb-3 jumbo-subtext subtitle-description-mobile">Markitplace is a platform designed to help chefs. For chefs that are new to operating their own business, we walk you through all steps to get you started. For existing chefs we help grow your customer base through our platform and provide insightful analytics on industry trends and customer needs. </h3>
            <h6 class="subtitle-description-mobile"> *Please note that we are offering our services free of charge for the forseeable future to support our partners
            during this difficult time. </h6>
        </div>
        </div>
    </div>
    </section>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-6 align-items-stretch pb-5">
                <h3 class="service-offering-mobile">Kitchen Space</h3>
                <p class="service-offering-text-mobile">Have a great idea or product, but not quite sure where to make it? We’ll help you secure a spot to make your business thrive.
                </p>
            </div>
            <div class="col-12 col-lg-6 pb-5">
                <h3 class="service-offering-mobile">Higher Earnings Potential</h3>
                <p class="service-offering-text-mobile">You make the food, you make the profit. Markitplace enables chefs to own, operate, and sell their own takeaway or delivery brand.
                </p>
            </div>
            <div class="col-12 col-lg-6 align-items-stretch pb-5">
                <h3 class="service-offering-mobile">Analytics</h3>
                <p class="service-offering-text-mobile">Monthly Analytics reports will include success of growth campaigns and other key metrics around the performance of the partnership. Our platform
                also actively seeks out user feedback which is condensed and presented to our partners so they can make actionable change.
                </p>
            </div>
            <div class="col-12 col-lg-6 pb-5">
                <h3 class="service-offering-mobile">Logistics Made Easier</h3>
                <p class="service-offering-text-mobile">Markitplace provides a booking platform for your customers, order management features, and analytics on your products. You focus on the food, we’ll focus on everything else. 
                </p>
            </div>
            <div class = "col-12 text-center">
                <%= link_to "APPLY NOW", partner_contact_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
            </div>
        </div>
    </div>
</div>

app/views/static_pages/privacy_policy.html.erb
<div class="pt-3 container justify-content-center terms-page">
    <h1 class="text-center"> PRIVACY POLICY <h1>
    <iframe class="terms-of-service" src="https://drive.google.com/file/d/127cMB_CYpGgtHB6-3AybYh_qMjIj8lhf/preview" width="640" height="480"></iframe>
</div>

app/views/static_pages/stripe_partner_info.html.erb
<div class = "container">
    <div class="row">
        <div class = "col-12 text-center"
            <h1>Partner Account Lookup</h1>
            <p>note that account numbers for stripe themselves are not compromsing</p>
        </div> 
    </div>
    <table class="table">
        <thead>
            <tr>
                <th scope="col">Partner Email</th>
                <th scope="col">Account ID </th>
            </tr>
        </thead>
        <tbody>
            <% @stripe_users.each do |user| %>
                <tr>
                    <td><%= user.stripe_email %></td>
                    <td><%= user.stripe_id %></td>
                </tr>
            <% end %>
        </tbody>
    </table>
</div>

app/views/static_pages/terms_of_service.html.erb
<div class="pt-3 container justify-content-center terms-page">
    <h1 class="text-center"> TERMS OF SERVICE <h1>
    <iframe class="terms-of-service" src="https://drive.google.com/file/d/1A_PnAk5uBRNrAYtz7_HR-nEemC6WOdV8/preview" width="640" height="480"></iframe>
</div>