config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/test', to: 'one_off_products#test_item'
  get '/test-index', to: 'one_off_products#test_index'
  delete '/test', to: 'carts#post_destroy'
  get '/test-index', to:'carts#post_index'
  get '/test-checkout', to: 'carts#post_checkout'
  post '/test-checkout', to: 'carts#post_complete_checkout'
  get '/send-test-email', to: 'carts#test_email'
  get '/beta-mailing-list', to: 'static_pages#beta_test_list'
  get '/home-signup-successful', to: 'stripe_connect_user#new'
  get '/our-team', to: 'static_pages#our_team'
  # get '/add-to-cart', to: 'carts#add_to_cart'
  post '/add-to-cart', to: 'carts#add_to_cart'
  get '/guest-add-to-cart', to: 'carts#guest_add_to_cart'
  post '/guest-add-to-cart', to: 'carts#post_guest_add_to_cart'
  get '/guest-cart', to: 'carts#guest_cart_index'
  delete '/guest-cart', to: 'carts#guest_destroy'
  get '/guest-checkout', to: 'carts#guest_checkout'
  post '/guest-checkout', to: 'carts#guest_complete_checkout'
  get 'add-subscription-to-cart', to: 'carts#add_to_cart_subscription'
  get '/checkout', to: 'carts#checkout'
  post '/checkout', to: 'carts#complete_checkout'
  get '/successful-checkout', to: 'cartss#successful_checkout'
  get '/unsuccessful-checkout', to: 'carts#unsuccessful_checkout'
  get '/cart', to: 'carts#index'
  delete '/cart', to: 'carts#destroy'
  get '/contact', to: 'static_pages#contact'
  get '/contact-test', to: 'static_pages#contact_test'
  post '/contact', to: 'static_pages#create'
  get '/services', to: 'static_pages#partners'
  post '/services', to: 'static_pages#partners_create'
  get '/partner-contact', to: 'static_pages#partner_contact'
  get '/terms-of-service', to: 'static_pages#terms_of_service'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/stripe-partners', to: 'static_pages#stripe_partner_info'
  get '/start-your-mealkit-program', to: 'static_pages#start_your_mealkit_program'
  get '/signup-info', to: 'users#business_or_customer'
  post '/signup-info', to: 'users#business_or_customer_create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # get '/plan-types', to: 'plan_types#index'
  get '/mealkits', to: 'products#index'
  get '/additional-products', to: 'one_off_products#index'
  get '/partners', to: 'partner_logos#index'
  get '/mealkit-playbook', to: 'partner_logos#playbook'
  post '/mealkit-playbook', to: 'partner_logos#download_playbook'
  resources :users
  resources :stripe_connect_users
  get '/successful-subscription-purchase', to: 'plan_types#successful_subscription_purchase'
  get '/unsuccessful-subscription-purchase', to: 'plan_types#unsuccessful_subscription_purchase'
  #Below routes specifically for product library
  # resources :products, only: [:index]
  #little bit of logic to determine where you should go
  resources :products do
    member do
      put "add", to: "products#library"
      put "remove", to: "products#library"
    end
  end
  #Look into the pricing controller needed here?
  # Resources pricing, only: [:index]
  resources :one_off_products
  resources :products
  resources :product_subscription_library, only: [:index] 

  ####MEAL KIT PLAN ROUTE SETUP######
  resources :plan_types do
    member do
      put "add", to: "plan_types#library"
      put "remove", to: "plan_types#library"
    end
  end
  resources :plan_types 
  resources :plan_subscription_library, only: [:index]
  resources :carts
  resources :partners, param: :name
  resources :partner_backgrounds

  ######BASIC SETUP ROUTES#######
  resources :subscriptions
  resources :purchase_one_offs
  resources :partner_logos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contact_emails, only: [:edit]

  #For Sitemap capture
  get '/sitemap.xml.gz', to: redirect("https://markitplace-sitemaps.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz")
end

app/models/one_off_product.rb
class OneOffProduct < ApplicationRecord
    #May need to change this depending on when we add the ID
    #Uncomment this when we have stripe mechanism down
    # validates :stripe_id, presence: true
    has_one_attached :thumbnail
    #belongs_to :user, through: :cart
    has_many :carts
    has_many :users, through: :carts
    #See if this works
    #has_many :quantities
    #Try Line Items
    has_many :line_items
    #For the quantity - need a nested attribute?
    #accepts_nested_attributes_for :brands
    #Again what you're doing here is linking each product to a user 
    #via the subscription libraries. Can think of it as a massive join. 
    #may need to rethink the relationship between product and subscription libraries
    #Need to think about thow this linkage is going to work... want the libraries to include subscriptions?
    #Might want to have something that shows past orders?
    # has_many :product_subscription_libraries
    # has_many :added_products, through: :product_subscription_libraries, source: :user
end

app/controllers/one_off_products_controller.rb
class OneOffProductsController < ApplicationController
    #May need to add library type to before action for set_product
    before_action :set_product_type, only: [:edit, :show, :update, :destroy]
    before_action :admin_user, except: [:index, :show, :test_item]

    def index
        #Show all the one-offs
        @one_off_products = OneOffProduct.order(:sort_priority, :out_of_stock)
    end

    #Actions and methods for testing items
    def test_item
        @one_off_product = OneOffProduct.find(19)
        # flash[:danger] = params
    end

    def test_index
        @one_off_products = OneOffProduct.order(:out_of_stock)
        @partners = PartnerLogo.all
    end
    #Regular methods again
    def new
        @one_off_product = current_user.one_off_products.build
    end
    
    def show
    end

    def edit
    end

    #This is where we'll link to stripe to create the one-off-product
    #SKU only letting us set a certain amount... need to think about this
    def create
        #Going to create the plan on behalf of the client - need key
        Stripe.api_key = Rails.application.credentials.production[:stripe_api_key]
        @one_off_product = current_user.one_off_products.build(one_off_product_params)
        #Create a new product and a new SKU
        stripe_product = Stripe::Product.create({
            #Might need to include a pricing input value here so it's dynamic and not hard-coded.
            #Also need to figure out what the billing period for this would be.
            name: @one_off_product.name,
            description: @one_off_product.description,
            type: "good",
            # amount_decimal: (@plan_type.price * 100),
            # currency: 'usd'
          },
          {stripe_account: @one_off_product.stripe_id})
          @one_off_product.update_attribute(:product_id, stripe_product.id)

        respond_to do |format|
            if @one_off_product.save
                flash[:success] = params
                format.html { redirect_to @one_off_product, success: 'ONE OFF PRODUCT was successfully created.' }
                format.json { render :show, status: :created, location: @one_off_product }
                flash[:warning] = "Make sure you update the credentials file with product ID"
               # @plan_type.plan_type_id = stripe_plan.id
               # @plan_type.save
            else
                flash[:danger] = "SOME TYPE OF ISSUE WITH CREATION"
                flash[:notice] = @one_off_product.errors.full_messages
                format.html { render :new }
                format.json { render json: @one_off_product.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        #Going to create the plan on behalf of the client - need key
        Stripe.api_key = Rails.application.credentials.production[:stripe_api_key]
        #@one_off_product = current_user.one_off_products.build(one_off_product_params)
        #Create a new product and a new SKU

        respond_to do |format|
            if @one_off_product.update(one_off_product_params)
                flash[:success] = params
                format.html { redirect_to @one_off_product, success: 'ONE OFF PRODUCT was successfully created.' }
                format.json { render :show, status: :created, location: @one_off_product }
                flash[:warning] = "Make sure you update the credentials file with product ID"
               # @plan_type.plan_type_id = stripe_plan.id
               # @plan_type.save
            else
                flash[:danger] = "SOME TYPE OF ISSUE WITH CREATION"
                flash[:notice] = @one_off_product.errors.full_messages
                format.html { render :new }
                format.json { render json: @one_off_product.errors, status: :unprocessable_entity }
            end
        end
        stripe_product = Stripe::Product.create({
            #Might need to include a pricing input value here so it's dynamic and not hard-coded.
            #Also need to figure out what the billing period for this would be.
            name: @one_off_product.name,
            description: @one_off_product.description,
            type: "good",
          },
          {stripe_account: @one_off_product.stripe_id})
          @one_off_product.update_attribute(:product_id, stripe_product.id)
    end

    #Need to buil in a way to destroy the product at some point
    def destroy
        @one_off_product.destroy
        respond_to do |format|
            format.html { redirect_to one_off_products_path, success: 'Product was successfully deleted.' }
            format.json { head :no_content }
        end
    end


    private

    def set_product_type
        @one_off_product = OneOffProduct.find(params[:id])
    end

    def one_off_product_params
        params.require(:one_off_product).permit(:name, :description, :extended_description, :available_cities, :delivery_schedule, :product_id, :price, :partner_name, :partner_background_link, :user_id, :calories, :fats, :servings, :prep_time, :created_at, :updated_at, :stripe_id, :is_trial, :out_of_stock, :flavor_options, :thumbnail)
    end

    #This is not DRY. Pulling from users controller
    def admin_user
        redirect_to(root_path) unless current_user.admin?
    end

    def generate_flavor_options_list(flavor_options)
        flavor_options.split(",")
    end
    helper_method :generate_flavor_options_list
end

app/views/one_off_products/_one_off_product.html.erb
<div class="card see-cooking" style="width: 18rem;">
    <%= link_to one_off_product_path(one_off_product) do %>
        <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt:"Meal Kit Plan Image" %>
        <div class="textOverlay">
            <div class="showText">More Info</div>
        </div>
    <% end %>
    <div class="card-body text-center">
        <h5 class="card-title text-center"> <%= one_off_product.name %></h5>
        <h6 class="card-subtitle mb-2 text-muted text-center"> <%= one_off_product.description %></h6>
        <% if logged_in? %>
            <% if current_user.admin? %>
                <%= link_to "More Info", one_off_product_path(one_off_product), class:"btn btn-success" %>
                <%= link_to "Edit Plan", edit_one_off_product_path(one_off_product), class: "btn btn-warning" %>
                <%= link_to 'Delete Product Exsitence- CAREFUL', one_off_product_path(one_off_product), data: {confirm: "Are you sure you want to delete this one_off_product?"}, method: :delete, class: "btn btn-danger" %>
            <% elsif current_user.is_subscribed? %>
                <%= link_to "Unsubscribe", subscription_path(one_off_product, connected_acct: one_off_product.stripe_id, plan_id: current_user.stripe_subscription_id[one_off_product.name.downcase]), data: {confirm: "Are you sure you want to unsubscribe from this plan?"}, method: :delete, class:"btn btn-danger" %>
            <% else %>
                <%= link_to "More Info", one_off_product_path(one_off_product), class:"btn btn-success" %>
            <% end %>
        <% else %>
            <%= link_to "More Info", one_off_product_path(one_off_product), class:"btn btn-success" %>
        <% end %> 
    </div>
</div>

app/views/one_off_products/guest_cart_index.html.erb
<% provide(:title, "Test Index") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <section class="jumbotron jumbotron-fluid home-jumbotron jumbotron-mobile" id='jumbotron-plans'>
          <div class="container">
            <div class="row text-left">
              <div class="col-7 col-lg-5 justify-content-center" id="jumbo-textbox">
                <h1 class="homepage-text shadow-underscore jumbo-maintext title-larger-mobile">Single Kits</h1>
                <h3 class ="homepage-text pt-3 pb-3" id ="jumbo-subtext">Check out single kits available from Our Partners</h3>
                <a href="#plan-offerings"><i class="fas fa-chevron-circle-down fa-3x scroll-down btn-fa-mobile" style="color: #449900;"></i></a>
              </div>
            </div>
          </div>
        </section>
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <%  @one_off_products.each do |one_off_product| %>
                    <% if one_off_product.hide? != "yes" %>
                        <div class="col-12 col-lg-4 pb-3 d-flex align-items-stretch card-padding-mobile">
                            <div class="card see-cooking card-width">
                                <%= link_to one_off_product_path(one_off_product) do %>
                                    <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                    <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                        <div class="showTextIndex align-middle text-center subtitle-mobile">See what&#39;s cooking</div>
                                    </div>
                                <% end %>
                                <div class="d-flex flex-column card-body text-center">
                                    <h4 class="card-title text-center title-card-mobile mt-auto"> <%= one_off_product.name %></h4>
                                    <p class="card-subtitle mb-2 text-center subtitle-description-mobile mt-auto" style="color:black"> <%= one_off_product.description %></p>
                                    <h5 class="text-center title-mobile mt-auto" style= "color:green">$<%= number_with_precision(one_off_product.price, precision: 2) %></h5>
                                    <% if logged_in? %>
                                        <% if current_user.admin? %>
                                            <%= link_to "Edit Product", edit_one_off_product_path(one_off_product), class: " mt-auto btn btn-warning btn-mobile" %>
                                            <%= link_to 'Delete Product', one_off_product_path(one_off_product), data: {confirm: "mt-auto Are you sure you want to delete this product?"}, method: :delete, class: "btn btn-danger btn-mobile" %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/one_off_products/index.html.erb
<% provide(:title, "Single Kits") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <section class="jumbotron jumbotron-fluid home-jumbotron jumbotron-mobile" id='jumbotron-plans'>
          <div class="container">
            <div class="row text-left">
              <div class="col-7 col-lg-5 justify-content-center" id="jumbo-textbox">
                <h1 class="homepage-text shadow-underscore jumbo-maintext title-larger-mobile">Kits</h1>
                <h3 class ="homepage-text pt-3 pb-3" id ="jumbo-subtext">Support small business in your community with a one-time meal kit purchase.</h3>
                <a href="#plan-offerings"><i class="fas fa-chevron-circle-down fa-3x scroll-down btn-fa-mobile" style="color: #449900;"></i></a>
              </div>
            </div>
          </div>
        </section>
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <%  @one_off_products.each do |one_off_product| %>
                    <% if one_off_product.hide != "yes" %>
                        <div class="col-12 col-lg-4 pb-3 d-flex align-items-stretch card-padding-mobile">
                            <div class="card see-cooking card-width">
                                <%= link_to one_off_product_path(one_off_product) do %>
                                    <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                    <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                        <div class="showTextIndex align-middle text-center subtitle-mobile">See what&#39;s cooking</div>
                                    </div>
                                <% end %>
                                <div class="d-flex flex-column card-body text-center">
                                    <h4 class="card-title text-center title-card-mobile mt-auto"> <%= one_off_product.name %></h4>
                                    <p class="card-subtitle mb-2 text-center subtitle-description-mobile mt-auto" style="color:black"> <%= one_off_product.description %></p>
                                    <h5 class="text-center title-mobile mt-auto" style= "color:green">$<%= number_with_precision(one_off_product.price, precision: 2) %></h5>
                                    <% if one_off_product.servings != nil %>
                                        <% price_per_serving = (one_off_product.price / one_off_product.servings).to_f %>
                                        <h5 class="text-center title-mobile mt-auto" style= "color:green">Price per Meal: $<%= number_with_precision(price_per_serving, precision: 2) %></h5>
                                    <% end %>
                                    <% if logged_in? %>
                                        <% if current_user.admin? %>
                                            <%= link_to "Edit Product", edit_one_off_product_path(one_off_product), class: " mt-auto btn btn-warning btn-mobile" %>
                                            <%= link_to 'Delete Product', one_off_product_path(one_off_product), data: {confirm: "mt-auto Are you sure you want to delete this product?"}, method: :delete, class: "btn btn-danger btn-mobile" %>
                                        <% end %>
                                    <% end %>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/one_off_products/new.html.erb
<% provide(:title, 'New Plan') %>

<div class='container'>
  <div class="row topspace-lg justify-content-center">
    <div class= "col-12">
      <h1 style = "text-align:center">New One-Off Product</h1>
    </div>
    <div class="card col-md-6 col-md-offset-3">
      <div class="card-body placeholder">
        <%= render 'one_off_product_form' %>
      </div>
    </div>
  </div>
</div>
      

app/views/one_off_products/show.html.erb
<% provide(:title, @one_off_product.name) %>
<div class = "container recipe-overview  mt-4 justify-content-center">
  <section class= "container">
    <div class = "recipe-header pt-2">
      <div class = "row pb-5">
        <div class = "col-12 text-center pb-2">
          <h1 class "pb-1 title-mobile"><%= @one_off_product.name %> </h1>
        </div>
        <div class= "col-12 col-lg-7 text-center recipe-header-button">
          <%= image_tag(@one_off_product.thumbnail, class:"img-fluid", alt: "Product Image") %>
        </div>
        <div class = "col-12 col-lg-5 text-center my-auto">
          <% if @one_off_product.calories != nil && @one_off_product.fats != nil %>
            <div class = "recipe-intro d-flex pt-3">
              <ul class= "stats list-inline mx-auto justify-content-center">
                <li class = "list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.calories %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Calories 
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.fats %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Grams of Fat
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.servings %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Servings
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.prep_time %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Prep Time
                  </div>
                </li>
              </ul>
            </div>
          <% elsif @one_off_product.servings != nil && @one_off_product.prep_time != nil %>
            <div class = "recipe-intro d-flex pt-3">
              <ul class= "stats list-inline mx-auto justify-content-center">
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.prep_time %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Prep Time
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    Serves <%= @one_off_product.servings %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Meal Kit Size
                  </div>
                </li>
              </ul>
            </div>
          <% else %>
            <div class = "recipe-intro d-flex pt-3">
              <ul class= "stats list-inline mx-auto justify-content-center">
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile test">
                    <%= Serves <%= @one_off_product.servings %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                   Meal Kit Size
                  </div>
                </li>
              </ul>
            </div>
          <% end %>
          <% if @one_off_product.extended_description != nil %>
            <p class="description-text subtitle-mobile"> <%= @one_off_product.extended_description %></p>
          <% else %>
            <p class="description-text subtitle-mobile"> <%= @one_off_product.description %></p>
          <% end %>
          <%= form_for(:item_options, url: add_to_cart_path) do |f| %>
            <% if @one_off_product.flavor_options != nil %>
              <% flavor_list = generate_flavor_options_list(@one_off_product.flavor_options) %>
              <%= f.label :flavor_options, class: 'field-label emphasis contact-form-item-mobile' do %>
                <% if @one_off_product.partner_name == "Jaju Pierogi" %>
                  <% size = "(Choose 1 or 2 Flavors)" %>
                <% else %>
                  <% size = "" %>
                <% end %>
                <span class = 'field-label emphasis'> Flavor: <%= size %>  </span>
              <% end %><br>
              <div style = "form-row">
                <% flavor_list.each do |flavor| %>
                  <%= f.check_box :flavor_option, {multiple: true, class: "checkbox-mobile"}, flavor, false %>
                  <%= f.label flavor, class: "subtitle-description-mobile" %><br>
                <% end %>
              </div>
            <% end %>
            <%= f.label :quantity, class: 'field-label emphasis contact-form-item-mobile subtitle-mobile' do %>
              <strong><span class = 'field-label emphasis'> Quantity: </span></strong>
            <% end %>
            <%= f.number_field :quantity, class: 'form-control form-control-width mx-auto form-control-mobile', placeholder: "1", style: "width: 25%" %>
            <%= hidden_field_tag(:one_off_product, @one_off_product.id) %>
            <%= f.submit "ADD TO CART", class: "btn btn-outline-success jumbo-button mt-2 btn-mobile" %><br>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/one_off_products/test_code.html.erb
<div class= "col-12 text-center our-team-descr image-overlay">
          <span class"image-overlay">
            <%= image_tag(@one_off_product.thumbnail, class:"img-fluid hover-green", alt: "Product Image") %>
            <div class="textOverlay">
              <div class="showTextOurTeam adjust-size founder-description-mobile text-center" style="display: inline-block">
                <h5 class="founder-description-mobile"><%= @one_off_product.name %> </h5>
                <p class="subtext-about about-description-mobile">
                  <%= @one_off_product.description %>
                </p>
              </div>
            </div>
          </span>
        </div>
      </div>
    

      <%= form_for(:quantity, url: one_off_product_path) do |f| %>
        <%= f.label :quantity, class: 'field-label emphasis contact-form-item-mobile' do %>
          <span class = 'field-label emphasis'> Quantity </span>
        <% end %>
        <%= f.number_field :quantity, class: 'form-control form-control-mobile', placeholder: "1" %><br>
      <% end %>

      <%= link_to 'ADD TO CART', add_to_cart_path(one_off_product: @one_off_product.name), class: "btn btn-outline-success jumbo-button btn-mobile" %>

app/views/one_off_products/test_item.html.erb
<% provide(:title, @one_off_product.name) %>
<div class = "container recipe-overview  mt-4 justify-content-center">
  <section class= "container">
    <div class = "recipe-header pt-2">
      <div class = "row pb-5">
        <div class = "col-12 text-center pb-2">
          <h1 class "pb-1 title-mobile"><%= @one_off_product.name %> </h1>
          <button class="btn btn-outline-success btn-mobile async-disable">Submit</button>
          <%= link_to "Send Test Email", send_test_email_path, class:"btn btn-outline-success jumbo-button btn-mobile" %>
          <iframe src= <%= @one_off_product.recipe_instructions_link %> width="640" height="480"></iframe>
        </div>
        <div class= "col-7 text-center recipe-header-button pb-2">
          <%= image_tag(@one_off_product.thumbnail, class:"img-fluid", alt: "Product Image") %>
        </div>
        <div class = "col-5 text-center mt-auto">
          <% if @one_off_product.calories != nil && one_off_product.fats != nil %>
            <div class = "recipe-intro d-flex pt-3">
              <ul class= "stats list-inline mx-auto justify-content-center">
                <li class = "list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.calories %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Calories 
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.fats %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Grams of Fat
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.servings %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Servings
                  </div>
                </li>
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.prep_time %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Prep Time
                  </div>
                </li>
              </ul>
            </div>  
          <% else %>
            <div class = "recipe-intro d-flex pt-3">
              <ul class= "stats list-inline mx-auto justify-content-center">
                <li class="list-inline-item">
                  <div class="stats-item subtitle-mobile">
                    <%= @one_off_product.prep_time %>
                  </div>
                  <div class="stats-subitem subtitle-mobile">
                    Prep Time
                  </div>
                </li>
              </ul>
            </div>
          <% end %>
          <% if @one_off_product.extended_description != nil %>
            <p class="description-text subtitle-description-mobile"> <%= @one_off_product.extended_description %></p>
          <% else %>
            <p class="description-text subtitle-description-mobile"> <%= @one_off_product.description %></p>
          <% end %>
          <% if logged_in? %>
            <%= form_for(:quantity, url: add_to_cart_path) do |f| %>
                <%= f.label :quantity, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> Quantity </span>
                <% end %>
                <%= f.number_field :quantity, class: 'form-control form-control-width mx-auto form-control-mobile', placeholder: "1" %>
                <%= hidden_field_tag(:one_off_product, @one_off_product.id) %>
                <%= f.submit "ADD TO CART", class: "btn btn-outline-success jumbo-button mt-2 btn-mobile" %><br>
            <% end %>
          <% else %>
            <div class = "pb-2">
              <% if @one_off_product.name == "Colossol Manhattan Package " %>
                <%= form_for(:sauce, url: guest_add_to_cart_path) do |f| %>
                  <%= f.label :sauce, class: 'field-label emphasis contact-form-item-mobile' do %>
                    <span class = 'field-label emphasis'> Sauce </span>
                  <% end %>
                  <%= f.select :sauce_choice, options_for_select([ "Chimichurri", "Pebre" ], "Chimichurri"), class: 'description-text subtitle-description-mobile pt-0 mt-0' %>
                  <%= hidden_field_tag(:one_off_product, @one_off_product.name) %>
                  <%= f.submit "ADD TO CART", class: "btn btn-outline-success jumbo-button mt-2 btn-mobile" %><br>
                <% end %>
              <% else %>
                <%= link_to 'START COOKING', guest_add_to_cart_path(one_off_product: @one_off_product.name), class:"btn btn-outline-success jumbo-button btn-mobile" %>
              <% end %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>