config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/test', to: 'one_off_products#test_item'
  get '/test-index', to: 'one_off_products#test_index'
  delete '/test', to: 'carts#post_destroy'
  get '/test-index', to:'carts#post_index'
  get '/test-checkout', to: 'carts#post_checkout'
  post '/test-checkout', to: 'carts#post_complete_checkout'
  get '/send-test-email', to: 'carts#test_email'
  get '/beta-mailing-list', to: 'static_pages#beta_test_list'
  get '/home-signup-successful', to: 'stripe_connect_user#new'
  get '/our-team', to: 'static_pages#our_team'
  # get '/add-to-cart', to: 'carts#add_to_cart'
  post '/add-to-cart', to: 'carts#add_to_cart'
  get '/guest-add-to-cart', to: 'carts#guest_add_to_cart'
  post '/guest-add-to-cart', to: 'carts#post_guest_add_to_cart'
  get '/guest-cart', to: 'carts#guest_cart_index'
  delete '/guest-cart', to: 'carts#guest_destroy'
  get '/guest-checkout', to: 'carts#guest_checkout'
  post '/guest-checkout', to: 'carts#guest_complete_checkout'
  get 'add-subscription-to-cart', to: 'carts#add_to_cart_subscription'
  get '/checkout', to: 'carts#checkout'
  post '/checkout', to: 'carts#complete_checkout'
  get '/successful-checkout', to: 'cartss#successful_checkout'
  get '/unsuccessful-checkout', to: 'carts#unsuccessful_checkout'
  get '/cart', to: 'carts#index'
  delete '/cart', to: 'carts#destroy'
  get '/contact', to: 'static_pages#contact'
  get '/contact-test', to: 'static_pages#contact_test'
  post '/contact', to: 'static_pages#create'
  get '/services', to: 'static_pages#partners'
  post '/services', to: 'static_pages#partners_create'
  get '/partner-contact', to: 'static_pages#partner_contact'
  get '/terms-of-service', to: 'static_pages#terms_of_service'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/stripe-partners', to: 'static_pages#stripe_partner_info'
  get '/start-your-mealkit-program', to: 'static_pages#start_your_mealkit_program'
  get '/signup-info', to: 'users#business_or_customer'
  post '/signup-info', to: 'users#business_or_customer_create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # get '/plan-types', to: 'plan_types#index'
  get '/mealkits', to: 'products#index'
  get '/additional-products', to: 'one_off_products#index'
  get '/partners', to: 'partner_logos#index'
  get '/mealkit-playbook', to: 'partner_logos#playbook'
  post '/mealkit-playbook', to: 'partner_logos#download_playbook'
  resources :users
  resources :stripe_connect_users
  get '/successful-subscription-purchase', to: 'plan_types#successful_subscription_purchase'
  get '/unsuccessful-subscription-purchase', to: 'plan_types#unsuccessful_subscription_purchase'
  #Below routes specifically for product library
  # resources :products, only: [:index]
  #little bit of logic to determine where you should go
  resources :products do
    member do
      put "add", to: "products#library"
      put "remove", to: "products#library"
    end
  end
  #Look into the pricing controller needed here?
  # Resources pricing, only: [:index]
  resources :one_off_products
  resources :products
  resources :product_subscription_library, only: [:index] 

  ####MEAL KIT PLAN ROUTE SETUP######
  resources :plan_types do
    member do
      put "add", to: "plan_types#library"
      put "remove", to: "plan_types#library"
    end
  end
  resources :plan_types 
  resources :plan_subscription_library, only: [:index]
  resources :carts
  resources :partners, param: :name
  resources :partner_backgrounds

  ######BASIC SETUP ROUTES#######
  resources :subscriptions
  resources :purchase_one_offs
  resources :partner_logos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contact_emails, only: [:edit]

  #For Sitemap capture
  get '/sitemap.xml.gz', to: redirect("https://markitplace-sitemaps.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz")
end

app/models/cart.rb
class Cart < ApplicationRecord
    belongs_to :user, optional: true
    belongs_to :guest_user, optional: true
    has_many :one_off_products
    has_many :plan_types
    serialize :products, Array
    # #Proper Checkout - institute checkout?
    has_many :line_items

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
    layout "test", only: [:post_checkout]

    #Need to build in code to modify the number of items you want in a cart
    def checkout
        @cart_items = current_user.cart.one_off_products
        @cart_items_subscriptions = current_user.cart.plan_types
        @total_price = sum_price(current_user.cart.one_off_products) + sum_price(current_user.cart.plan_types)
        # @intent = 
    end

    def guest_cart_index
        if logged_in?
            if cart_not_created?
                redirect_to root_path
                flash[:warning] = "Your Cart is currently empty!"
            elsif cart_empty?
                redirect_to root_path
                flash[:warning] = "Your Cart is currently empty!"
            else
                @cart_items = current_user.cart.one_off_products
                @cart_items_subscriptions = current_user.cart.plan_types
            end 
        else
            # if guest_cart_empty?
            #     redirect_to root_path
            #     flash[:warning] = "Your Cart is currently empty!"
            #     return
            # else
            if guest_cart.one_off_products == nil
                redirect_to root_path
                flash[warning] = "Cart is empty!"
                return
            elsif guest_cart.one_off_products.length < 1
                redirect_to root_path
                flash[:warning] = "Cart is empty!"
            else
                @cart_items = guest_cart.one_off_products
            end
            # redirect_to root_path
            # flash[:warning] = "Guest!"
            # end
        end
    end

    #Let's test the guest checkout
    def guest_checkout
        @cart_items = guest_cart.one_off_products
        @total_price = sum_price(guest_cart.one_off_products)
    end

    def index
        Stripe.api_key = Rails.application.credentials.production[:stripe_api_key]
        token = params[:stripeToken]
        if logged_in?
            if cart_not_created?
                redirect_to root_path
                # flash[:danger] = "cart not created"
                flash[:warning] = "Your Cart is currently empty!"
            elsif cart_empty?
                redirect_to root_path
                # flash[:danger] = "Nothing in cart"
                flash[:warning] = "Your Cart is currently empty!"
            else
                @cart_items = current_user.cart.line_items
            end 
        else
            if guest_cart.line_items == nil
                redirect_to root_path
                flash[:warning] = "Cart is empty!"
                return
            elsif guest_cart.line_items.length < 1
                redirect_to root_path
                flash[:warning] = "Cart is empty!"
            else
                @cart_items = guest_cart.line_items
            end
        end
        #Check to see if anyting in cart and then create session
        if @cart_items != nil
            #Then create the stripe call
            line_items_array = Array.new() 
            @cart_items.each do |line_item|
                if line_item.flavor_option == nil
                    line_item.flavor_option = ""
                end
                meal_kit = find_one_off_by_id(line_item.product_id)
                item_hash = {
                    price_data: {
                    currency: 'usd',
                    product_data: {
                        name: meal_kit.name + "-"+ line_item.flavor_option,
                    },
                    #Should this be to_i? Revisit
                    unit_amount: (meal_kit.price.to_i)*100,
                    },
                    quantity: line_item.quantity,
                }
                line_items_array << item_hash
            end
            #Initiate Stripe Session Call
            session_id = request.session_options[:id]
            #THIS IS NOT DRY CODE. NEED TO IMPROVE
            if logged_in?
                session = Stripe::Checkout::Session.create(
                    #Customer email is only paramter changed
                    customer_email: current_user.email,
                    payment_method_types: ['card'],
                    shipping_address_collection: {
                        allowed_countries: ['US'],
                    },
                    line_items: line_items_array,
                    mode: 'payment',
                    success_url: "https://www.markitplace.io/successful-checkout?session_id=#{session_id}",
                    cancel_url: 'https://www.markitplace.io/unsuccessful-checkout',
                )
            else
                session = Stripe::Checkout::Session.create(
                    payment_method_types: ['card'],
                    shipping_address_collection: {
                        allowed_countries: ['US'],
                    },
                    line_items: line_items_array,
                    mode: 'payment',
                    success_url: "https://www.markitplace.io/successful-checkout?session_id=#{session_id}",
                    cancel_url: 'https://www.markitplace.io/unsuccessful-checkout',
                )
            end
            @session = session
        end
    end

    def successful_checkout
        if user_signed_in?
            current_user.cart.line_items.delete_all
        else
            guest_cart.line_items.delete_all
            # flash[:warning] = guest_cart.line_items
        end
        #OrderConfirmationMailer.single_kit_order.deliver_now
        flash[:success] = "Your order has been received! You will receive an email confirmation shortly."
        redirect_to root_path
    end

    def unsuccessful_checkout
        flash[:danger] = "Your checkout session didn't complete. Please try again"
        redirect_to cart_path
    end

    #Method specifically for guests adding to cart

    #Modify specifically for tge sauce. Not good long term
    def guest_add_to_cart
        item = (params[:one_off_product]).downcase
        one_off = find_one_off(item)
        # flash[:success] = guest_cart
        # @cart guest_cart
        if one_off.out_of_stock == nil || one_off.out_of_stock != "yes"
            guest_cart.one_off_products << one_off
            guest_cart.save
            flash[:success] = "Item has been added to your shopping cart!"
            redirect_to one_off_products_path
        else
            flash[:warning] = "Unfortunately this item is out of stock. Please try another!"
            redirect_to one_off_products_path
        end
    end

    def post_guest_add_to_cart
        item = (params[:one_off_product]).downcase
        one_off = find_one_off(item)
        #update the sauce - this will need to be changed
        # flash[:warning] = params[:sauce]
        if one_off.id == 80 || one_off.id == 81 || one_off.id == 82 || one_off.id == 84
            one_off.add_on = params[:sauce][:sauce_choice]
            one_off.save
        end
        # @cart guest_cart
        if one_off.out_of_stock == nil || one_off.out_of_stock != "yes"
            guest_cart.one_off_products << one_off
            guest_cart.save
            flash[:success] = "Item has been added to your shopping cart!"
            redirect_to one_off_products_path
        else
            flash[:warning] = "Unfortunately this item is out of stock. Please try another!"
            redirect_to one_off_products_path
        end
    end

    #Run on the local server first --> Need to test
    def add_to_cart
        item = params[:one_off_product]
        #Specify quantity when adding to cart --> Need to add to form
        quantity = (params[:item_options][:quantity]).to_i
        if quantity == 0
            quantity = 1
        end
        #Probably should change this to ID
        one_off = find_one_off_by_id(item)
        # flash[:danger] = params[:quantity]
        line_item = LineItem.new()
        line_item.product_id = item
        if one_off.flavor_options != "" && one_off.flavor_options != nil
            flavor_array = params[:item_options][:flavor_option]
            flavor_string = ""
            flavor_array.each do |flavor|
                flavor_string += flavor
                flavor_string+= ", "
            end
            flavor_string = flavor_string[0..-3]
            line_item.flavor_option = flavor_string
            # flash[:warning] = flavor_string
        end
        line_item.quantity = quantity
        line_item.product_type = "One Off Product"
        if logged_in?
            if cart_not_created?
                testCart = Cart.new()
                current_user.cart = testCart
            end
            current_user.cart.line_items << line_item
            current_user.cart.save
        #If user is a guest
        else
            guest_cart.line_items << line_item
            guest_cart.save
        end
        flash[:success] = "Item has been added to your shopping cart!"
        redirect_to one_off_products_path
    end

    def post_add_to_cart
        item_id = params[:one_off_product]
        if params[:quantity][:quantity] == nil
            quantity = 1
        else
            quantity = (params[:quantity][:quantity]).to_i
        end
        # quantity = quantity.to_i
        # flash[:danger] = quantity
        one_off = find_one_off_by_id(item_id)
        if one_off.out_of_stock == nil
            if cart_not_created?
                testCart = Cart.new()
                current_user.cart = testCart
            end
        # elsif one_off.out_of_stock.downcase == "yes"
        #     flash[:warning] = "Unfortunately this item is out of stock. Please try another!"
        #     redirect_to one_off_products_path
        #     return
        else
            if cart_not_created?
                # empty_cart = Cart.create(products: [])
                testCart = Cart.new()
                current_user.cart = testCart
            end 
        end
        #Instantiate Line Item
        line_item = LineItem.new()

app/views/carts/checkout.html.erb
<% provide(:title, 'Checkout') %>
<div class = "container subscription-overview  mt-4 justify-content-center">
  <section class= "container">
    <div class = "subscription-header pt-2">
      <div class = "row">
        <div class = "col-12 col-lg-6 checkout-header">
            <h1 class="title-larger-mobile">Checkout</h1>
            <h4 class = "title-mobile strong-mobile">Order Summary: $<%= number_with_precision(@total_price, precision: 2) %> </h4>
            <% @cart_items.each do |item| %>
              <div class = "row pb-3 mobile-hide">
                  <div class = "col-12 col-lg-6">
                      <%= image_tag item.thumbnail.variant(resize: "450x450"), class: "img-fluid" %>
                  </div>
                  <div class = "col-12 col-lg-6">
                      <h5><%= item.name %></h5>
                      <p> <%= item.description %></p>
                  </div>
              </div>
          <% end %>
          <% @cart_items_subscriptions.each do |item| %>
            <div class = "row pb-3 mobile-hide">
                <div class = "col-12 col-lg-6">
                    <%= image_tag item.thumbnail.variant(resize: "450x450"), class: "img-fluid" %>
                </div>
                <div class = "col-12 col-lg-6">
                    <h5 class="title-mobile"><%= item.name %></h5>
                    <p class="subtitle-mobile"><%= item.description %></p>
                </div>
            </div>
        <% end %>

        </div>
        <div class= "col-12 col-lg-6 checkout-header">
          <%= form_for(:payment_shipping, url: checkout_path, html: {id: "payment-form"}) do |f| %>
            <div class="shipping-information">
              <h1 class="title-mobile">Shipping Information</h1>
              <%= f.label :recipient_name, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> Name </span>
              <% end %>
              <%= f.text_field :recipient_name, class: 'form-control form-control-mobile', placeholder: "Name" %>
              <%= f.label :street_address_1, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> Street Address 1 </span>
              <% end %>
              <%= f.text_field :street_address_1, class: 'form-control form-control-mobile', placeholder: "Street Address" %>
              <%= f.label :street_address_2, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> Street Address (Room/Apt Number) </span>
              <% end %>
              <%= f.text_field :street_address_2, class: 'form-control form-control-mobile', placeholder: "Street Address" %>
              <%= f.label :city, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> City </span>
              <% end %>
              <%= f.text_field :city, class: 'form-control form-control-mobile', placeholder: "City" %>
              <%= f.label :state, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> State </span>
              <% end %>
              <%= f.text_field :state, class: 'form-control form-control-mobile', placeholder: "State" %>
              <%= f.label :zipcode, class: 'field-label emphasis contact-form-item-mobile' do %>
                <span class = 'field-label emphasis'> Zipcode </span>
              <% end %>
              <%= f.number_field :zipcode, class: 'form-control form-control-mobile', placeholder: "Zipcode" %><br>
            </div>
            <div class="payment-information">
              <h1 class="title-mobile">Card Information</h1>
              <div class="field card-information">
                <label for="card-element" class="field-label emphasis contact-form-item-mobile ">Enter credit or debit card</label>
                <div id="card-element">
                  <!-- A Stripe Element will be inserted here. -->
                </div>
                <br>
      
                <div id="card-errors" role="alert"></div>
      
                <%= hidden_field_tag :plan_id, params[:plan_id] %>
                <%= hidden_field_tag :plan_name, params[:plan_name] %>
                <button class="btn btn-outline-success btn-mobile">Submit</button>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </section>
</div>

app/views/carts/guest_cart_index.html.erb
<% provide(:title, "Cart") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <div class = "col-12 pb-3 text-center">
                    <h1 class = "title-larger-mobile">Your Cart </h1><br>
                    <%= link_to "Checkout", guest_checkout_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
                </div>
                <%  @cart_items.each do |one_off_product| %>
                    <div class="d-flex col-12 col-lg-4 pb-3 align-items-stretch card-padding-mobile">
                        <div class="card see-cooking card-width">
                            <%= link_to one_off_product_path(one_off_product) do %>
                                <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                    <div class="showTextIndex align-middle text-center subtitle-description-mobile">See what&#39;s cooking</div>
                                </div>
                            <% end %>
                            <div class="card-body text-center d-flex flex-column">
                                <h5 class="card-title text-center title-card-mobile"> <%= one_off_product.name %></h5>
                                <h6 class="text-center title-mobile">$<%= number_with_precision(one_off_product.price, precision: 2) %></h6>
                                <h6 class="card-subtitle mb-2 text-muted text-center subtitle-description-mobile pb-2"> <%= one_off_product.description %></h6>
                                <%= link_to "Remove from Cart", guest_cart_path(one_off_product: one_off_product.name), data: {confirm: "Are you sure you want to remove this from our cart?"}, method: :delete, class: "btn btn-danger btn-mobile mt-auto" %> 
                            </div>
                        </div>
                    </div>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/carts/index.html.erb
<% provide(:title, "Cart") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <div class = "col-12 pb-3 text-center">
                    <h1 class = "title-larger-mobile">Your Cart </h1><br>
                    <button id="checkout-button" class= "btn btn-mobile btn-outline-success jumbo-button" data-secret="<%= @session.id %>"> Checkout </button>
                </div>
                <%  @cart_items.each do |line_item| %>
                    <% one_off_product = find_one_off_by_id(line_item.product_id) %>
                    <div class="d-flex col-12 col-lg-4 pb-3 align-items-stretch card-padding-mobile">
                        <div class="card see-cooking card-width">
                            <%= link_to one_off_product_path(one_off_product) do %>
                                <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                    <div class="showTextIndex align-middle text-center subtitle-description-mobile">See what&#39;s cooking</div>
                                </div>
                            <% end %>
                            <div class="card-body text-center d-flex flex-column">
                                <h5 class="card-title text-center title-card-mobile"> <%= one_off_product.name %></h5>
                                <h6 class="text-center title-mobile"><%= line_item.flavor_option %></h6>
                                <h6 class="text-center title-mobile">$<%= number_with_precision(one_off_product.price, precision: 2) %></h6>
                                <h6 class="text-center title-mobile">Quantity: <%= line_item.quantity %></h6>
                                <%= link_to "Remove from Cart", cart_path(one_off_product: line_item.id), data: {confirm: "Are you sure you want to remove this from our cart?"}, method: :delete, class: "btn btn-danger btn-mobile mt-auto" %> 
                            </div>
                        </div>
                    </div>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/carts/post_index.html.erb
<% provide(:title, "Cart") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <div class = "col-12 pb-3 text-center">
                    <h1 class = "title-larger-mobile">Your Cart </h1><br>
                    <%= link_to "Checkout", test_checkout_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
                </div>
                <%  @cart_items.each do |line_item| %>
                    <% one_off_product = find_one_off_by_id(line_item.product_id) %>
                    <div class="d-flex col-12 col-lg-4 pb-3 align-items-stretch card-padding-mobile">
                        <div class="card see-cooking card-width">
                            <%= link_to one_off_product_path(one_off_product) do %>
                                <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                    <div class="showTextIndex align-middle text-center subtitle-description-mobile">See what&#39;s cooking</div>
                                </div>
                            <% end %>
                            <div class="card-body text-center d-flex flex-column">
                                <h5 class="card-title text-center title-card-mobile"> <%= one_off_product.name %></h5>
                                <h6 class="text-center title-mobile">$<%= one_off_product.price %></h6>
                                <h6 class="text-center title-mobile">Quantity: <%= line_item.quantity %></h6>
                                <h6 class="card-subtitle pb-2 text-muted text-center subtitle-description-mobile pb-2"> <%= one_off_product.description %></h6>
                                <%= link_to "Remove from Cart", test_path(product_id: line_item.product_id, product_type: line_item.product_type), data: {confirm: "Are you sure you want to remove this from our cart?"}, method: :delete, class: "btn btn-danger btn-mobile mt-auto" %> 
                            </div>
                        </div>
                    </div>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/carts/test_code.html.erb
<% @cart_items.each do |item| %>
    <div class = "row pb-3">
        <div class = "col-6">
            <%= image_tag item.thumbnail.variant(resize: "450x450"), class: "img-fluid" %>
        </div>
        <div class = "col-6">
            <h5><%= item.name %></h5>
            <%= item.description %>
        </div>
    </div>
<% end %>

<%= form_for(:product_name, url: cart_path), html: {id: "quantity-form"}) do |f| %>
    <%= f.label :quantity, class: 'field-label emphasis contact-form-item-mobile' do %>
        <span class = 'field-label emphasis'> Quantity </span>
    <% end %>
    <%= f.number_field :quantity, class: 'form-control form-control-mobile', placeholder: "Quantity" %><br>
<% end %>
<%= f.number_field :quantity, class: 'form-control form-control-mobile', placeholder: "Zipcode" %><br>

app/views/carts/test_index.html.erb
<% provide(:title, "Cart") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <div class = "col-12 pb-3 text-center">
                    <h1 class = "title-larger-mobile">Your Cart </h1><br>
                    <%= link_to "Checkout", guest_checkout_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
                </div>
                <%  @cart_items.each do |one_off_product| %>
                    <div class="d-flex col-12 col-lg-4 pb-3 align-items-stretch card-padding-mobile">
                        <div class="card see-cooking card-width">
                            <%= link_to one_off_product_path(one_off_product) do %>
                                <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                    <div class="showTextIndex align-middle text-center subtitle-description-mobile">See what&#39;s cooking</div>
                                </div>
                            <% end %>
                            <div class="card-body text-center d-flex flex-column">
                                <h5 class="card-title text-center title-card-mobile"> <%= one_off_product.name %></h5>
                                <h6 class="text-center title-mobile">$<%= number_with_precision(one_off_product.price, precision: 2) %></h6>
                                <h6 class="card-subtitle mb-2 text-muted text-center subtitle-description-mobile pb-2"> <%= one_off_product.description %></h6>
                                <%= link_to "Remove from Cart", guest_cart_path(one_off_product: one_off_product.name), data: {confirm: "Are you sure you want to remove this from our cart?"}, method: :delete, class: "btn btn-danger btn-mobile mt-auto" %> 
                            </div>
                        </div>
                    </div>
                <% end %>
            <div>
        </div>
    </div>
</div>

app/views/carts/view_cart.html.erb
<% provide(:title, "Cart") %>
<div class="plan-homepage">
    <div class="plan-homepage-2019">
        <div class="container" id="plan-offerings">
            <div class="row ml-3">
                <div class = "col-12 pb-3 text-center">
                    <h1>Your Cart </h1><br>
                    <%= link_to "Checkout", checkout_path, class: "btn btn-outline-success jumbo-button btn-mobile" %>
                </div>
                <%  @cart_items.each do |one_off_product| %>
                    <div class="col-12 col-lg-4 pb-3 d-flex align-items-stretch card-padding-mobile">
                        <div class="card see-cooking card-width">
                            <%= link_to one_off_product_path(one_off_product) do %>
                                <%= image_tag one_off_product.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                                <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                    <div class="showTextIndex align-middle text-center subtitle-description-mobile">See what&#39;s cooking</div>
                                </div>
                            <% end %>
                            <div class="card-body text-center">
                                <h5 class="card-title text-center title-card-mobile"> <%= one_off_product.name %></h5>
                                <h6 class="text-center title-mobile">$<%= one_off_product.price %></h6>
                                <h6 class="card-subtitle mb-2 text-muted text-center subtitle-description-mobile"> <%= one_off_product.description %></h6>
                            </div>
                        </div>
                    </div>
                <% end %>
            <div>
        </div>
    </div>
</div>