config/routes.rb
Rails.application.routes.draw do
  get 'password_resets/new'
  get 'password_resets/edit'
  get 'sessions/new'
  root 'static_pages#home'
  get '/test', to: 'one_off_products#test_item'
  get '/test-index', to: 'one_off_products#test_index'
  delete '/test', to: 'carts#post_destroy'
  get '/test-index', to:'carts#post_index'
  get '/test-checkout', to: 'carts#post_checkout'
  post '/test-checkout', to: 'carts#post_complete_checkout'
  get '/send-test-email', to: 'carts#test_email'
  get '/beta-mailing-list', to: 'static_pages#beta_test_list'
  get '/home-signup-successful', to: 'stripe_connect_user#new'
  get '/our-team', to: 'static_pages#our_team'
  # get '/add-to-cart', to: 'carts#add_to_cart'
  post '/add-to-cart', to: 'carts#add_to_cart'
  get '/guest-add-to-cart', to: 'carts#guest_add_to_cart'
  post '/guest-add-to-cart', to: 'carts#post_guest_add_to_cart'
  get '/guest-cart', to: 'carts#guest_cart_index'
  delete '/guest-cart', to: 'carts#guest_destroy'
  get '/guest-checkout', to: 'carts#guest_checkout'
  post '/guest-checkout', to: 'carts#guest_complete_checkout'
  get 'add-subscription-to-cart', to: 'carts#add_to_cart_subscription'
  get '/checkout', to: 'carts#checkout'
  post '/checkout', to: 'carts#complete_checkout'
  get '/successful-checkout', to: 'cartss#successful_checkout'
  get '/unsuccessful-checkout', to: 'carts#unsuccessful_checkout'
  get '/cart', to: 'carts#index'
  delete '/cart', to: 'carts#destroy'
  get '/contact', to: 'static_pages#contact'
  get '/contact-test', to: 'static_pages#contact_test'
  post '/contact', to: 'static_pages#create'
  get '/services', to: 'static_pages#partners'
  post '/services', to: 'static_pages#partners_create'
  get '/partner-contact', to: 'static_pages#partner_contact'
  get '/terms-of-service', to: 'static_pages#terms_of_service'
  get '/privacy-policy', to: 'static_pages#privacy_policy'
  get '/stripe-partners', to: 'static_pages#stripe_partner_info'
  get '/start-your-mealkit-program', to: 'static_pages#start_your_mealkit_program'
  get '/signup-info', to: 'users#business_or_customer'
  post '/signup-info', to: 'users#business_or_customer_create'
  get  '/signup',  to: 'users#new'
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # get '/plan-types', to: 'plan_types#index'
  get '/mealkits', to: 'products#index'
  get '/additional-products', to: 'one_off_products#index'
  get '/partners', to: 'partner_logos#index'
  get '/mealkit-playbook', to: 'partner_logos#playbook'
  post '/mealkit-playbook', to: 'partner_logos#download_playbook'
  resources :users
  resources :stripe_connect_users
  get '/successful-subscription-purchase', to: 'plan_types#successful_subscription_purchase'
  get '/unsuccessful-subscription-purchase', to: 'plan_types#unsuccessful_subscription_purchase'
  #Below routes specifically for product library
  # resources :products, only: [:index]
  #little bit of logic to determine where you should go
  resources :products do
    member do
      put "add", to: "products#library"
      put "remove", to: "products#library"
    end
  end
  #Look into the pricing controller needed here?
  # Resources pricing, only: [:index]
  resources :one_off_products
  resources :products
  resources :product_subscription_library, only: [:index] 

  ####MEAL KIT PLAN ROUTE SETUP######
  resources :plan_types do
    member do
      put "add", to: "plan_types#library"
      put "remove", to: "plan_types#library"
    end
  end
  resources :plan_types 
  resources :plan_subscription_library, only: [:index]
  resources :carts
  resources :partners, param: :name
  resources :partner_backgrounds

  ######BASIC SETUP ROUTES#######
  resources :subscriptions
  resources :purchase_one_offs
  resources :partner_logos
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :contact_emails, only: [:edit]

  #For Sitemap capture
  get '/sitemap.xml.gz', to: redirect("https://markitplace-sitemaps.s3.us-east-2.amazonaws.com/sitemaps/sitemap.xml.gz")
end

app/models/partner_background.rb
class PartnerBackground < ApplicationRecord
    #Just saying that each of these constructs have a thumbnail attached
    has_one_attached :thumbnail
end

app/controllers/partner_background_controller.rb
class PartnerBackgroundsController < ApplicationController
    before_action :set_partner_info, only: [:show, :edit, :update, :destroy]
    before_action :admin_user, except: [:show]

    #Need all these REST methods? Doubtful
    def index
        @partner_backgrounds = PartnerBackground.all
    end

    def new
        @partner_background = Partnerbackground.new
    end

    def create
        @partner_background = Partnerbackground.new(partner_background_params)
        if @partner_background.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @partner_background = Partnerbackground.find(params[:id])
    end

    def update
        @partner_background = PartnerInformaton.find(params[:id])
        if @partner_background.update_attributes(partner_background_params)
            flash[:success] = "The partner Info page has been updated"
            redirect_to root_path
        else
            render 'edit'
        end
    end
    
    def destroy
        Partnerbackground.find(params[:id]).destroy
        # flash[:warning] = params
        flash[:success] = "Partner Logo Deleted"
        redirect_to root_path
    end

    private

    def set_partner_info
        @parnter_background = Partnerbackground.find(params[:id])
    end

    def partner_background_params
        params.require(:partner_background).permit(:name, :tag_line, :description, :created_at, :updated_at, :thumbnail)
    end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/controllers/partner_backgrounds_controller.rb
class PartnerBackgroundsController < ApplicationController
    before_action :set_partner_info, only: [:show, :edit, :update, :destroy]
    before_action :admin_user, except: [:show]

    #Need all these REST methods? Doubtful
    def index
        @partner_backgrounds = PartnerBackground.all
    end

    def new
        @partner_background = PartnerBackground.new
    end

    def create
        @partner_background = PartnerBackground.new(partner_background_params)
        if @partner_background.save
            redirect_to root_path
        else
            render 'new'
        end
    end

    def edit
        @partner_background = PartnerBackground.find(params[:id])
    end

    def update
        @partner_background = PartnerBackground.find(params[:id])
        if @partner_background.update_attributes(partner_background_params)
            flash[:success] = "The partner Info page has been updated"
            redirect_to root_path
        else
            render 'edit'
        end
    end
    
    def destroy
        Partnerbackground.find(params[:id]).destroy
        # flash[:warning] = params
        flash[:success] = "Partner Logo Deleted"
        redirect_to root_path
    end

    private

    def set_partner_info
        @partner_background = PartnerBackground.find(params[:id])
    end

    def partner_background_params
        params.require(:partner_background).permit(:name, :tag_line, :description, :created_at, :updated_at, :thumbnail)
    end

    def admin_user
        redirect_to(root_url) unless current_user.admin?
    end
end

app/views/partner_backgrounds/_partner_background_form.html.erb
<%= form_for(@partner_background) do |f| %>
    <p class="subtext-gray pb-1" style="font-size:14px">Only admins should be able to
    access this page. </p>

    <%= f.text_field :name, class: 'form-control', placeholder: "Partner Name", required: true %><br>

    <%= f.text_field :tag_line, class: 'form-control', placeholder: "Tag Line", required: true %><br>

    <%= f.text_field :description,  class: 'form-control', placeholder: "Partner Descripton", required: true %><br>

    <%= f.label :thumbnail do %>
        <span class = 'field-label emphasis'> Partner Logo Image </span><br>
    <% end %><br>
    <%= f.file_field :thumbnail, multiple: false, required: true %> <br>
    <br>

    <%= f.submit "Submit", class: "btn btn-success btn-block form-actions" %><br>
<% end %>

app/views/partner_backgrounds/edit.html.erb
<% provide(:title, 'Edit Partner Information') %>
<div class='container'>
  <div class="row topspace-lg justify-content-center">
    <div class= "col-12">
      <h1 style = "text-align:center">Edit Partner Info</h1>
    </div>
    <div class="card col-md-6 col-md-offset-3">
      <div class="card-body placeholder">
        <%= render 'partner_information_form', partner_information: @partner_information %>
      </div>
    </div>
  </div>
</div>
      

app/views/partner_backgrounds/index.html.erb
<% provide(:title, "Partner Background") %>
<div class="parners-homepage">
    <div class="partners-homepage-2019">
        <div class = "text-center pt-2 pb-2">
            <h1>Our Partners (Internal Use Only) </h1>
        </div>
        <div class="container-fluid" id="partner-offerings">
            <%  @partner_backgrounds.each do |partner| %>
                <div class="col-12 col-lg-4 pb-3 d-flex align-items-stretch card-padding-mobile">
                    <div class="card see-cooking card-width">
                        <div class="ribbon-wrapper">
                            <div class="ribbon green"> <%= partner.name %> </div>
                        </div>
                        <%= link_to partner_background_path(partner) do %>
                            <%= image_tag partner.thumbnail.variant(resize: "450x450"), class:"card-img-top hover-gray", alt: "Meal Kit Plan Image" %>
                            <div class="textOverlay align-middle text-center subtitle-description-mobile">
                                <div class="showTextIndex align-middle text-center subtitle-mobile">See what&#39;s cooking</div>
                            </div>
                        <% end %>
                        <div class="d-flex flex-column card-body text-center">
                            <h4 class="card-title text-center title-card-mobile mt-auto"> <%= partner.name %></h4>
                            <p class="card-subtitle mb-2 text-center subtitle-description-mobile mt-auto" style="color:black"> <%= partner.tag_line %></p>
                            <% if logged_in? %>
                                <% if current_user.admin? %>
                                    <%= link_to "Edit Product", edit_partner_background_path(partner), class: " mt-auto btn btn-warning btn-mobile" %>
                                    <%= link_to 'Delete Product', partner_background_path(partner), data: {confirm: "mt-auto Are you sure you want to delete this product?"}, method: :delete, class: "btn btn-danger btn-mobile" %>
                                <% end %>
                            <% end %>
                        </div>
                    </div>
                </div>
            <% end %>
        </div>
    </div>
</div>

app/views/partner_backgrounds/new.html.erb
<% provide(:title, 'New Partner Background') %>
<div class='container'>
  <div class="row topspace-lg justify-content-center">
    <div class= "col-12">
      <h1 style = "text-align:center">New Partner Information</h1>
    </div>
    <div class="card col-md-6 col-md-offset-3">
      <div class="card-body placeholder">
        <%= render 'partner_background_form' %>
      </div>
    </div>
  </div>
</div>

app/views/partner_backgrounds/show.html.erb
<% provide(:title, @partner_background.name) %>
<div class = "container partner-background-overview partner-background-overview-mobile  mt-4 justify-content-center">
  <section class= "container">
    <div class = "recipe-header pt-2">
      <div class = "row pb-5">
        <div class = "col-12 text-center pb-2">
          <h1 class= "pb-1 title-mobile"><%= @partner_background.name %> </h1>
          <i><h4 class= "subtitle-mobile"><%= @partner_background.tag_line %></h4></i>
        </div>
        <div class= "col-12 text-center recipe-header-button">
          <%= image_tag(@partner_background.thumbnail, class:"img-fluid", alt: "Product Image") %>
        </div>
        <div class = "col-12 text-center my-auto pt-2">
            <p class="description-text subtitle-description-mobile"> <%= @partner_background.description %></p>     
        </div>
      </div>
    </div>
  </section>
</div>